# Para ejecutar los servidores:
# docker compose --profile all up -d

# Para listar los servidores:
# docker ps

# Para ver el log del nginx:
# docker compose logs -f nginx

# Para matar los servidores:
# docker compose --profile all down --remove-orphans


networks:
  proxy_develop:
    name: proxy_develop
    driver: bridge
    #ipam:
    #  config:
    #    - subnet: 10.2.0.0/28

services:
  nginx:
    profiles: [ "all" ]
    image: ${IMAGE_NGINX}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${WORKSPACE}/nginx_proxy/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      #- cache:/data/nginx/cache
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      proxy_develop:
        aliases:
          - nginx