swagger: "2.0"
info:
  title: "Nogales API"
  description: "API Gateway"
  version: "1.0.0"

schemes:
  - https
paths:
  /videocall:
    get:
      summary: "Videocall Service"
      description: "Videocall Service"
      operationId: "getGceService"
      responses:
        200:
          description: "Successful response from GCE service."
          schema:
            type: object
      x-google-backend:
        address: http://34.56.212.112
        path_translation: "CONSTANT_ADDRESS"
        #pathTranslation: "APPEND_PATH_TO_ADDRESS"
        #pathOverride: "/"