#docker compose -f docker-compose.yml --profile all up -d && docker compose -f docker-compose.yml logs -f wireguard
#docker compose -f docker-compose.yml --profile all down --remove-orphans
#docker compose -f docker-compose.yml logs -f wireguard

networks:
  network_vpn:
    name: network_vpn
    driver: bridge
    enable_ipv6: false

volumes:
  vpn_modules:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${WORKSPACE}/vpn_modules"
  vpn_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${WORKSPACE}/vpn_config"

# https://github.com/linuxserver/docker-wireguard
services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        environment:
            # External IP or domain name for docker host. 
            # Used in server mode. If set to auto, 
            # the container will try to determine and set 
            # the external IP automatically
            #- SERVERURL=wireguard.domain.com
            # Internal subnet for the wireguard and server and peers 
            # (only change if it clashes). Used in server mode.
            - INTERNAL_SUBNET=10.13.13.0
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - SERVERPORT=51820
            - PEERS=1
            - PEERDNS=auto
            - ALLOWEDIPS=0.0.0.0/0
            - PERSISTENTKEEPALIVE_PEERS=
            - LOG_CONFS=true
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        ports:
            - 51820:51820/udp
        volumes:
            - vpn_config:/config
            - vpn_modules:/lib/modules
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped

