# docker compose --profile all down --remove-orphans
# docker compose --profile all up -d
# docker compose --profile nginx up -d
# docker compose --profile nodeserver up -d
# docker compose logs -f nodeserver
# docker compose logs -f nginx

# docker compose down --volumes
# docker compose ps

# ssh root@localhost -p 2219

# http://localhost:4200/
# http://localhost:8081/srv/postgress/test

volumes:
  flowcharts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${FOLDER_CODE_CORE}/flowcharts"
  src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${FOLDER_CODE_CORE}/src"
  srv:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${FOLDER_CODE_CORE}/srv"
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${WORKSPACE}/postgres/data"
  bucket:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${BUCKET_FOLDER}"

networks:
  network_develop:
    name: network_develop
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  nginx:
    profiles: [ "all", "nginx" ]
    image: ${IMAGE_NGINX}
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "4200:4200"
    volumes:
      - ${WORKSPACE}/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - bucket:/etc/nginx/html
    restart: always
    #depends_on:
    #  nodeserver:
    #    condition: service_healthy
    networks:
      network_develop:
        aliases:
          - nginx

  # docker run -it us-docker.pkg.dev/ejfexperiments/us.gcr.io/nodeserverdev:v0.8.0 /bin/bash
  nodeserver:
    profiles: [ "all", "nodeserver" ]
    image: ${IMAGE_NODE_SERVER}
    environment:
      PORT: "8081"
      ENV: "pro"
      GOOGLE_APPLICATION_CREDENTIALS: ${GCP_SERVICE_ACCOUNT_JSON}
      FACE_SERVER: ""
      TRAIN_SERVER: ""
      WORKSPACE: "/tmp/app"
      USE_SECURE: ${USE_SECURE}
      MILVUS_URI: ${MILVUS_URI}
      MONGO_USR: ${MONGO_USR}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_URI: ${MONGO_URI}
      MINIO_USR: ${MINIO_USR}
      MINIO_PASS: ${MINIO_PASS}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URI: ${MINIO_URI}
      NODE_SERVER_PATH: /
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: nogales
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "2219:22"
      #- "8081:8081"
      #- "4200:4200"
    volumes:
      - "flowcharts:/tmp/app/flowcharts"
      - "src:/tmp/app/src"
      - "srv:/tmp/app/srv"
      - "${FOLDER_CODE_CORE}/app.mjs:/tmp/app/app.mjs"
      - "${FOLDER_CODE_CORE}/rundev.sh:/tmp/app/rundev.sh"
      - "${FOLDER_CODE_CORE}/package.json:/tmp/app/package.json"
    networks:
      network_develop:
        aliases:
          - nodeserver
    healthcheck:
      test: curl --fail http://localhost:8081/srv/shell?cmd=ls || exit 1
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 10s
    command: sh /tmp/app/rundev.sh

  postgres:
    profiles: [ "all" ]
    image: ${IMAGE_POSTGRES}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=nogales
    networks:
      network_develop:
        aliases:
          - postgres

  mongodb:
    profiles: [ "all" ]
    image: mongodb/mongodb-atlas-local
    command: sh /tmp/mongo/run.sh
    #user: "systemd-coredump"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USR}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - ${WORKSPACE}/mongo/run.sh:/tmp/mongo/run.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      network_develop:
        aliases:
          - mongodb
    healthcheck:
      test: test $$(mongosh --port 30001 --quiet --eval "try {rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo:30001\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
      retries: 20
